config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root "films#index"

  get "movies/filter/:filter" => "films#index", as: :filtered_movies
  resources :films do
    resources :reviews
    resources :favorites
  end

  resources :users
  get "signup" => "users#new"


  resource :session, only: [:new,:create,:destroy]
  get "signin" => "sessions#new"
end

app/models/film.rb
class Film < ApplicationRecord
  before_save :set_slug

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans , through: :favorites, source: :user
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations
  has_one_attached :main_image

  validates :name, presence: true, uniqueness: true
  validates :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validate :acceptable_image


  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }

  scope :released,-> { where("released_on < ?", Time.now).order("released_on desc") }
  scope :upcoming,-> { where("released_on > ?", Time.now).order("released_on desc") }
  scope :recent, -> (max=5) { released.limit(max) }
  scope :hits, -> { released.where("price >= 300000000").order(price: :desc) }
  scope :flops, -> { released.where("price < 22500000").order(price: :asc) }

  def average_stars
    reviews.average(:stars) || 0.0
  end


  def to_param
    slug
  end


  private

  def acceptable_image
    return unless main_image.attached?

    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(main_image.content_type)
      errors.add(:main_image, "must be a JPEG or PNG")
    end
  end

  def set_slug
    self.slug = name.parameterize
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :require_signin, except: [:index,:show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_film, only: [:destroy,:show,:edit,:update]

    def index
      case params[:filter]
      when "upcoming"
        @favorite_movies = Film.upcoming
      when "recent"
        @favorite_movies = Film.recent
      when "hits"
        @favorite_movies = Film.hits
      when "flops"
        @favorite_movies = Film.flops
      else
        @favorite_movies = Film.released
      end

    end

    def show

      @genres = @movie.genres.order(:name)
      @fans = @movie.fans
      if current_user
        @favorite = current_user.favorites.find_by(film_id: @movie.id)
      end
    end

    def edit
    end

    def update

      if @movie.update(movie_params)
        redirect_to @movie
      else
        render :update, notice: "Movie successfully updated!"
      end

    end

    def new
      @movie = Film.new
    end

    def create
     @movie = Film.new(movie_params)

     if @movie.save
        redirect_to @movie, notice: "Movie successfully created!"
     else
        render :new
     end

    end

    def destroy
      @movie.destroy

      redirect_to films_url, alert:  "Movie successfully deleted!"
    end

  end

  private

  def set_film
    @movie = Film.find_by!(slug: params[:id])
  end

    def movie_params
      params
      .require(:film)
      .permit(
          :name,
          :description,
          :price,
          :rating,
          :released_on,
          :duration,
          :director,
          :main_image,
          genre_ids: []
          )
    end

app/views/films/_form.html.erb
<%= form_with(model: movie,local:true) do |f|%>

  <%= render "shared/errors_messages", object: movie %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, {class: "date"} %>

  <%= f.label :rating %>
  <%= f.select :rating, Film::RATINGS, prompt: "Pick one" %>


  <%= f.label :description %>
  <%= f.text_area :description, rows: 7 %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :main_image %>
  <%= f.file_field :main_image %>

  <div class="checkboxes">
    <%= f.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name) %>
  </div>

  <%= f.submit %>

<% end %>

app/views/films/edit.html.erb
<h1>Editing <%= @movie.name %></h1>

<%= render "form", movie:@movie%>

app/views/films/index.html.erb
<div>
   <% @favorite_movies.each do |movie| %>
      <section class="movie">
         <div class="image">
            <%= main_image(movie) %>
         </div>
         <div class="summary">
            <h2>
               <%= link_to movie.name, film_path(movie) %>
            </h2>
            <h3>
               <%= isMovieFlop(movie) %>
            </h3>
            <p>
               <%= truncate(movie.description, length: 150, separator: ' ') %>
            </p>
         </div>
      </section>
   <% end %>

   <% if current_user_admin? %>
   <section class="admin">
      <%= link_to "Create Movie",new_film_path, class:"button"%>
   </section>
   <% end %>

   </div>

app/views/films/new.html.erb
<h1>Create new Movie</h1>

<%= render "form", movie:@movie %>

app/views/films/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= main_image(@movie) %>

    <% if current_user %>
      <div class="faves">

      <%= fave_or_unfave_button(@movie, @favorite) %>

      <div class="count">
      <%= @fans.size %>
      </div>

      </div>
    <% end %>

  </div>

  <div class="details">
    <h1><%= @movie.name %></h1>
    <h2>
      <%= movie_year(@movie) %> &bull <%= @movie.rating %>
    </h2>

    <span class="stars">
    <%= average_stars(@movie) %>
    </span>


    <p>

    <%= truncate(@movie.description, length: 150, separator: ' ') %>

    </p>

    <table>
      <tr>
        <th>Total Gross:</th>
        <td><%= isMovieFlop(@movie) %></td>
      </tr>
    </table>

    <%= link_to "Write Review", new_film_review_path(@movie),
    class: "review" %>

    <% if current_user_admin? %>
    <section class="admin">
      <%= link_to "Edit",edit_film_path, class:"button" %>
      <%= link_to "Delete", film_path, class:"button", method: :delete,
      data:{ confirm:" are you sure?" }
      %>
    </section>
    <% end %>
    </div>

    <aside>
      <% if @fans.present? %>
        <h4>Fans</h4>
        <ul>
          <% @fans.each do |user| %>
          <li>
            <%= link_to user.name, user %>
          </li>
          <% end %>
          </ul>
      <% end %>
      <% if @genres.present? %>
        <h4>Genres</h4>
        <ul>
          <% @genres.each do |g| %>
            <li><%= g.name %></li>
          <% end %>
        </ul>
      <% end %>
    </aside>
</section>